# Generated by Django 4.2.5 on 2023-10-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_link',
        ),
    ]
