# Generated by Django 4.2.5 on 2023-09-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('results', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.FileField(upload_to='datasets/', verbose_name='Dataset')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Uploaded at')),
                ('store_category', models.CharField(choices=[('ELECTRONIC', 'Electronic'), ('CLOTHES', 'Clothes')], max_length=10, verbose_name='Store category')),
            ],
        ),
    ]
