# Generated by Django 4.2.5 on 2023-09-27 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET('Absent'), to=settings.AUTH_USER_MODEL, verbose_name='Business Owner'),
        ),
        migrations.AddField(
            model_name='analyzeddataset',
            name='the_dataset',
            field=models.ForeignKey(null=True, on_delete=models.SET('Absent'), to='business.dataset', verbose_name='The dataset'),
        ),
        migrations.AddField(
            model_name='analyzeddataset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET('Absent'), to=settings.AUTH_USER_MODEL, verbose_name='Business Owner'),
        ),
    ]
